import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: Readonly<{ 
  children: React.ReactNode;
}>) {

  const headersList = headers();
  // const domain = headersList.get("x-forwarded-host") || "";
  // const protocol = headersList.get("x-forwarded-proto") || "";
  const pathname = headersList.get("x-invoke-path") || "";

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col bg-white">
          {children}
        </div>
      </body>
    </html>
  );
}
